trigger: none

pool:
  name: internal-agent

variables:
  tag: "$(Build.BuildId)"
  appName: apigateway

resources:
  - repo: self

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        variables:
          - group: internal
        steps:
          - task: Bash@3
            displayName: Build and Push Image to Azure Container Registry
            inputs:
              targetType: inline
              script: |
                cd $(Build.SourcesDirectory)/APIGatewayMVC
                podman build -f $(Build.SourcesDirectory)/APIGatewayMVC/Dockerfile -t $(appName):$(tag) .
                podman create -ti --name $(appName) $(appName):$(tag)
                podman cp $(appName):/app/testresults/ $(Build.ArtifactStagingDirectory)/testresults 
                podman rm -fv $(appName)

# podman login -u $(internalSP) -p $(internalSPSecret) $(acrName)
# podman push $(appName):$(tag) $(acrName)/$(appName):$(tag)

# - stage: Deploy
#   displayName: Deploy image to AKS
#   jobs:
#   - job: ApplyKubernetesJob
#     displayName: 'Apply Kubernetes Job'
#     variables:
#     - group: dev
#     steps:
#     - task: KubeloginInstaller@0
#       inputs:
#         kubeloginVersion: 'latest'

#     - task: replacetokens@5
#       inputs:
#         rootDirectory: '$(Build.SourcesDirectory)'
#         targetFiles: '**/migration-service.yaml'
#         encoding: 'auto'
#         tokenPattern: 'azpipelines'
#         writeBOM: true
#         actionOnMissing: 'warn'
#         keepToken: false
#         actionOnNoFiles: 'warn'
#         enableTransforms: false
#         enableRecursion: false
#         useLegacyPattern: false
#         enableTelemetry: true

#     - task: Kubernetes@1
#       displayName: Create Job $(appName)
#       env:
#         imageVersion: "latest"
#       inputs:
#         connectionType: 'Azure Resource Manager'
#         azureSubscriptionEndpoint: 'internal-adm-sp'
#         azureResourceGroup: 'internal-ptae-rg-01'
#         kubernetesCluster: 'internal-ptae-aks-01'
#         namespace: $(envName)
#         command: 'apply'
#         arguments: '-f $(Build.SourcesDirectory)/migration-service.yaml'
#         secretType: 'dockerRegistry'
#         containerRegistryType: 'Azure Container Registry'

