# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
- repo: self

trigger:
  none
  
variables:
  system.debug: true
  
stages:
- stage: Deploy
  displayName: Deploy api and run apigateway
  jobs:
  - job: 
    displayName: Deploy api and run apigateway
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'ssh_to_hyve_dev_vps'
        targetFolder: 'apigateway'
        contents: |
                  **
        readyTimeout: '20000'
    - task: SSH@0
      inputs:
        sshEndpoint: 'ssh_to_hyve_dev_vps'
        failOnStdErr: false
        runOptions: 'commands'
        commands: |
           sudo docker compose -f ~/apigateway/APIGatewayMVC/docker-compose.yml up -d
        readyTimeout: '20000'
    
