# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '5826a18b-ffba-49d5-84a1-8124f8883f52'
  imageRepository: 'apigateway'
  containerRegistry: 'ptaeventscontainerregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/APIGatewayMVC/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push image to container registry
  jobs:
  - job: Build
    displayName: Build and push image to container registry
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
